#!/usr/bin/env python3
"""Exploratory: does knowing how much of a team is NEW help in September?

Not wired into the model. The question it answers is narrow: the 20-week
lookback in weeks 1-4 is mostly last season, and last season's team may not
exist any more -- so does a measure of how much of it survived predict where
the model goes wrong early?

Two signals, both computed per team-season:

  continuity   how much of last season's team is still here. Offense is
               weighted by PRODUCTION (share of last year's offensive EPA
               generated by players on this week's roster), because losing a
               0.25-EPA receiver is not the same as losing a replacement one.
               Defense is weighted by SNAPS, because play-by-play only names
               a tackler or two and cannot attribute defensive value fairly.

  market prior a power rating per team implied by the market's own week-1
               spreads (ridge-fit: spread = away rating - home rating - home
               field). This is the closest free stand-in for preseason win
               totals, which nflverse does not carry -- import_win_totals is
               per-game lines, not season totals, despite the name.

Weekly rosters, not seasonal ones: a seasonal roster includes players who
signed in November, which would leak the future into a week-1 number.

    python roster_study.py --seasons 2013-2025      # build the cache
    python roster_study.py --report                 # what it correlates with
"""
import argparse
from pathlib import Path

import numpy as np
import pandas as pd

CACHE = Path('data/roster')
RELOCATED = {'SD': 'LAC', 'STL': 'LA', 'OAK': 'LV'}
HOME_FIELD_PRIOR = 2.0


def offensive_production(season):
    """{(team, player_id): EPA} for one season's offensive plays, credited to
    whoever touched the ball. A player's value to a team is what he did for
    that team, so the key carries posteam."""
    plays = pd.read_parquet(f'data/pbp/pbp_{season}.parquet',
                            columns=['posteam', 'epa', 'passer_player_id',
                                     'rusher_player_id', 'receiver_player_id'])
    plays = plays[plays.posteam.notna() & plays.epa.notna()]
    credited = []
    for column in ['passer_player_id', 'rusher_player_id', 'receiver_player_id']:
        part = plays[plays[column].notna()][['posteam', column, 'epa']]
        credited.append(part.rename(columns={column: 'player_id'}))
    stacked = pd.concat(credited, ignore_index=True)
    stacked['team'] = stacked.posteam.replace(RELOCATED)
    # Value, not volume: a player who cost his team EPA still occupied a role,
    # so continuity uses the magnitude of involvement.
    stacked['weight'] = stacked.epa.abs()
    return stacked.groupby(['team', 'player_id']).weight.sum()


def defensive_snaps(season):
    """{(team, pfr_player_id): defensive snaps}. Snap counts come from
    Pro-Football-Reference and carry PFR ids, not the gsis ids play-by-play
    uses -- the weekly roster carries both, which is how the two sides get
    compared against the same roster."""
    import nfl_data_py as nfl
    snaps = nfl.import_snap_counts([season])
    snaps = snaps[snaps.defense_snaps.notna() & snaps.pfr_player_id.notna()]
    snaps['team'] = snaps.team.replace(RELOCATED)
    return snaps.groupby(['team', 'pfr_player_id']).defense_snaps.sum()


def roster_at(season, week):
    """{team: {'gsis': ids, 'pfr': ids}} as the roster stood that week.

    Both id systems, because production is credited in gsis ids and snaps in
    PFR ids. Weekly, not seasonal: a seasonal roster includes players who
    signed in November, which would leak the future into a week-1 number."""
    import nfl_data_py as nfl
    weekly = nfl.import_weekly_rosters([season])
    weekly = weekly[weekly.week <= week]
    weekly['team'] = weekly.team.replace(RELOCATED)
    latest = weekly.sort_values('week').drop_duplicates(['team', 'player_id'], keep='last')
    return {team: {'gsis': set(group.player_id.dropna()), 'pfr': set(group.pfr_id.dropna())}
            for team, group in latest.groupby('team')}


def continuity(season, week=1):
    """Per team: the share of last season's production and defensive snaps
    still on the roster this week. 1.0 means everyone who mattered is back."""
    offense, defense = offensive_production(season - 1), defensive_snaps(season - 1)
    rosters = roster_at(season, week)
    def share(weights, kept):
        return weights[weights.index.isin(kept)].sum() / weights.sum() if weights.sum() else np.nan

    offense_teams = set(offense.index.get_level_values('team'))
    defense_teams = set(defense.index.get_level_values('team'))
    rows = []
    for team in sorted(offense_teams | defense_teams):
        here = rosters.get(team, {'gsis': set(), 'pfr': set()})
        rows.append(dict(
            season=season, team=team,
            offense_continuity=share(offense.loc[team], here['gsis']) if team in offense_teams else np.nan,
            defense_continuity=share(defense.loc[team], here['pfr']) if team in defense_teams else np.nan))
    frame = pd.DataFrame(rows)
    frame['continuity'] = frame[['offense_continuity', 'defense_continuity']].mean(axis=1)
    return frame


def market_prior(season, through_week=1, ridge=1.0):
    """A power rating per team from the market's own lines through
    `through_week`, by least squares with a ridge pull toward average:
    spread_line (home perspective) = home rating - away rating + home field.

    Week 1 alone is 16 equations for 32 unknowns, so the ridge is doing real
    work -- this is a shrunken estimate, not a solved one. It stands in for
    the preseason win totals nflverse does not carry."""
    sched = pd.read_parquet('data/sched.parquet')
    games = sched[(sched.season == season) & (sched.week <= through_week) & sched.spread_line.notna()]
    games = games.replace({'away_team': RELOCATED, 'home_team': RELOCATED})
    teams = sorted(set(games.away_team) | set(games.home_team))
    index = {team: i for i, team in enumerate(teams)}
    design = np.zeros((len(games), len(teams)))
    for row, game in enumerate(games.itertuples()):
        design[row, index[game.home_team]] = 1.
        design[row, index[game.away_team]] = -1.
    observed = games.spread_line.to_numpy() - HOME_FIELD_PRIOR
    ratings = np.linalg.solve(design.T @ design + ridge * np.eye(len(teams)), design.T @ observed)
    return pd.DataFrame(dict(season=season, team=teams, market_prior=ratings - ratings.mean()))


def build(seasons):
    CACHE.mkdir(parents=True, exist_ok=True)
    frames = []
    for season in seasons:
        print(f'  {season}...', flush=True)
        frame = continuity(season).merge(market_prior(season), on=['season', 'team'], how='outer')
        frames.append(frame)
    table = pd.concat(frames, ignore_index=True)
    table.to_parquet(CACHE / 'continuity.parquet')
    print(f'{len(table)} team-seasons -> {CACHE / "continuity.parquet"}')
    return table


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--seasons', default='2013-2025', help='Range to build, e.g. 2013-2025')
    parser.add_argument('--report', action='store_true', help='Analyse an existing cache')
    args = parser.parse_args(argv)
    if args.report:
        table = pd.read_parquet(CACHE / 'continuity.parquet')
        print(table.groupby('season')[['offense_continuity', 'defense_continuity', 'market_prior']]
                   .agg(['mean', 'std']).round(3).to_string())
        return
    first, last = (int(x) for x in args.seasons.split('-'))
    build(range(first, last + 1))


if __name__ == '__main__':
    main()


# --------------------------------------------------------------- cap value
def cap_values(seasons):
    """(gsis_id, season) -> share of the salary cap that player counted for.

    From each contract's season_history, which breaks a deal down year by
    year -- so this is what a player was worth IN 2017, not what his current
    deal says. cap_percent rather than dollars because the cap triples over
    the span and raw salary would make every recent player look like a star.

    A value proxy, not a value: rookie-deal stars are underpaid, declining
    veterans overpaid, and quarterbacks dwarf the scale. Treat it as one
    noisy read on how much a departure cost."""
    import nfl_data_py as nfl
    contracts = nfl.import_contracts()
    contracts = contracts[contracts.gsis_id.notna()]
    rows = []
    for player, history in zip(contracts.gsis_id, contracts.season_history):
        if history is None or len(history) == 0:
            continue
        for year in history:
            season = pd.to_numeric(year.get('year'), errors='coerce')
            if pd.notna(season) and int(season) in seasons:
                rows.append((player, int(season), year.get('cap_percent'), year.get('cap_number')))
    table = pd.DataFrame(rows, columns=['player_id', 'season', 'cap_percent', 'cap_number'])
    # A player can appear twice in a year (traded, restructured); the largest
    # cap hit is the one that describes what he was worth to somebody.
    return table.sort_values('cap_percent').drop_duplicates(['player_id', 'season'], keep='last')


def talent_flux(season, week=1):
    """Per team: the cap share that walked out the door and the share that
    walked in, measured on LAST season's prices so a new signing is valued by
    what someone paid for him rather than by what he later became.

    The counterpart to continuity, which counts how much stayed. A team can
    keep 60% of its production and still be rebuilt if the 40% it lost was
    its three most expensive players."""
    values = cap_values({season - 1}).set_index('player_id').cap_percent
    before, now = roster_at(season - 1, 22), roster_at(season, week)
    rows = []
    for team in sorted(set(before) | set(now)):
        was = before.get(team, {'gsis': set()})['gsis']
        is_ = now.get(team, {'gsis': set()})['gsis']
        left, joined, kept = was - is_, is_ - was, was & is_
        rows.append(dict(season=season, team=team,
                         cap_out=values.reindex(list(left)).fillna(0).sum(),
                         cap_in=values.reindex(list(joined)).fillna(0).sum(),
                         cap_kept=values.reindex(list(kept)).fillna(0).sum()))
    frame = pd.DataFrame(rows)
    frame['cap_flux'] = frame.cap_in - frame.cap_out
    return frame


def implied_team_totals(seasons=None):
    """The market's own view of each team's scoring, per game, which needs no
    new source: a game total of 47 with the home team favoured by 3 says 25
    and 22. In week 1 this is the only opinion anyone has about a rebuilt
    team, which is exactly when the model's own stats are least trustworthy."""
    sched = pd.read_parquet('data/sched.parquet')
    games = sched[sched.spread_line.notna() & sched.total_line.notna()].copy()
    if seasons is not None:
        games = games[games.season.isin(list(seasons))]
    games = games.replace({'away_team': RELOCATED, 'home_team': RELOCATED})
    games['away_implied'] = (games.total_line - games.spread_line) / 2
    games['home_implied'] = (games.total_line + games.spread_line) / 2
    return games[['season', 'week', 'game_id', 'away_team', 'home_team',
                  'spread_line', 'total_line', 'away_implied', 'home_implied']]


# ------------------------------------------------------- yards retained
def yards_retained(season, week=1, qb_weight=.65):
    """Per team: what share of last season's yards was produced by players
    still on the roster this week.

    Production is credited to whoever touched the ball, which is the version
    that actually discriminates -- weighting whole plays by their personnel
    mix does not, because the same eleven run nearly every snap (spread of
    0.10 against 0.23 here).

    Passing yards are credited twice on purpose, once to the quarterback and
    once to the receiver, and kept in separate columns because they answer
    different questions. `pass_offense` combines them with the quarterback
    carrying `qb_weight`, since a team returning its passer and nobody else
    is in a very different position from one returning everybody but him."""
    plays = pd.read_parquet(f'data/pbp/pbp_{season - 1}.parquet',
                            columns=['posteam', 'pass', 'rush', 'yards_gained',
                                     'passer_player_id', 'rusher_player_id', 'receiver_player_id'])
    plays = plays[plays.posteam.notna() & plays.yards_gained.notna()]
    plays['team'] = plays.posteam.replace(RELOCATED)
    rosters = roster_at(season, week)

    def share(team, phase, credit):
        own = plays[plays.team.eq(team) & plays[phase].eq(1) & plays[credit].notna()]
        here = rosters.get(team, {'gsis': set()})['gsis']
        total = own.yards_gained.sum()
        return own[own[credit].isin(here)].yards_gained.sum() / total if total else np.nan

    rows = []
    for team in sorted(t for t in plays.team.unique() if isinstance(t, str)):
        qb = share(team, 'pass', 'passer_player_id')
        receiver = share(team, 'pass', 'receiver_player_id')
        rows.append(dict(season=season, team=team, pass_by_qb=qb, pass_by_receiver=receiver,
                         rush_retained=share(team, 'rush', 'rusher_player_id'),
                         pass_offense=qb_weight * qb + (1 - qb_weight) * receiver))
    return pd.DataFrame(rows)


def build_retention(seasons):
    CACHE.mkdir(parents=True, exist_ok=True)
    table = pd.concat([yards_retained(s) for s in seasons], ignore_index=True)
    table.to_parquet(CACHE / 'yards_retained.parquet')
    print(f'{len(table)} team-seasons -> {CACHE / "yards_retained.parquet"}')
    return table


# --------------------------------------------------- preseason win totals
WIN_TOTALS_URL = 'https://raw.githubusercontent.com/nflverse/nfldata/master/data/win_totals.csv'


def win_totals(refresh=False):
    """The preseason over/under on each team's season wins, 2003 on.

    The market's whole-offseason opinion of a team in one number, formed with
    everything the model cannot see -- roster moves, the draft, coaching
    changes, holdouts. For a team that turned over half its roster it is the
    only informed prior that exists in week 1, when the model's own lookback
    is still describing last year's team.

    nflverse/nfldata, not nfl_data_py: import_win_totals there is per-game
    moneyline/spread/total lines despite the name, and covers two seasons."""
    CACHE.mkdir(parents=True, exist_ok=True)
    path = CACHE / 'win_totals.parquet'
    if path.exists() and not refresh:
        return pd.read_parquet(path)
    table = pd.read_csv(WIN_TOTALS_URL)
    table['team'] = table.team.replace(RELOCATED)
    table.to_parquet(path)
    return table


# ------------------------------------------------------- retention by unit
OLINE_POS = {'T', 'G', 'C', 'OL', 'OT', 'OG'}
PASS_DEF_POS = {'CB', 'DB', 'S', 'SS', 'FS'}
RUN_DEF_POS = {'DT', 'NT', 'DE', 'LB', 'ILB', 'OLB', 'MLB', 'DL'}
CATCHER_POS = {'WR', 'TE'}
BACK_POS = {'RB', 'FB'}


def _name_key(value):
    """Snap counts and rosters share no usable id for offensive linemen --
    weekly rosters list them as position OL with 0% pfr_id coverage, and the
    public crosswalks are built from fantasy sources that ignore them
    entirely (936 corners, 1 centre). Matching on a normalised name recovers
    97% of linemen, against 0% by id."""
    import re
    text = str(value).lower().replace('.', '').replace("'", '')
    text = re.sub(r'\s+(jr|sr|ii|iii|iv|v)$', '', text.strip())
    return re.sub(r'[^a-z ]', '', text)


def unit_retention(season, week=1):
    """Per team, the share of last season's production or snaps retained by
    each unit. The quarterback is deliberately absent: qb_elo already carries
    him, and folding him in here would count the one position the model
    handles best twice."""
    import nfl_data_py as nfl
    prior = season - 1
    weekly = nfl.import_weekly_rosters([prior]).drop_duplicates('player_id')
    weekly['team'] = weekly.team.replace(RELOCATED)
    weekly['key'] = weekly.player_name.map(_name_key)
    position = weekly.set_index('player_id').position

    snaps = nfl.import_snap_counts([prior])
    snaps['team'] = snaps.team.replace(RELOCATED)
    snaps['key'] = snaps.player.map(_name_key)
    by_name = weekly.drop_duplicates(['team', 'key']).set_index(['team', 'key']).player_id
    snaps['gsis'] = pd.MultiIndex.from_arrays([snaps.team, snaps.key]).map(by_name)

    plays = pd.read_parquet(f'data/pbp/pbp_{prior}.parquet',
                            columns=['posteam', 'pass', 'rush', 'yards_gained',
                                     'rusher_player_id', 'receiver_player_id'])
    plays = plays[plays.posteam.notna() & plays.yards_gained.notna()]
    plays['team'] = plays.posteam.replace(RELOCATED)
    rosters = roster_at(season, week)

    def yards(team, phase, credit, positions):
        own = plays[plays.team.eq(team) & plays[phase].eq(1) & plays[credit].notna()]
        own = own[own[credit].map(position).isin(positions)]
        here = rosters.get(team, {'gsis': set()})['gsis']
        total = own.yards_gained.sum()
        return own[own[credit].isin(here)].yards_gained.sum() / total if total else np.nan

    def snap(team, column, positions):
        own = snaps[snaps.team.eq(team) & snaps[column].gt(0) & snaps.position.isin(positions)]
        here = rosters.get(team, {'gsis': set()})['gsis']
        total = own[column].sum()
        return own[own.gsis.isin(here)][column].sum() / total if total else np.nan

    rows = []
    for team in sorted(t for t in plays.team.unique() if isinstance(t, str)):
        rows.append(dict(season=season, team=team,
                         receivers=yards(team, 'pass', 'receiver_player_id', CATCHER_POS),
                         backs=yards(team, 'rush', 'rusher_player_id', BACK_POS),
                         oline=snap(team, 'offense_snaps', {'T', 'G', 'C'}),
                         pass_def=snap(team, 'defense_snaps', PASS_DEF_POS),
                         run_def=snap(team, 'defense_snaps', RUN_DEF_POS)))
    return pd.DataFrame(rows)


def build_unit_retention(seasons):
    CACHE.mkdir(parents=True, exist_ok=True)
    table = pd.concat([unit_retention(s) for s in seasons], ignore_index=True)
    table.to_parquet(CACHE / 'unit_retention.parquet')
    print(f'{len(table)} team-seasons -> {CACHE / "unit_retention.parquet"}')
    return table


def incoming_cap(season, week=1):
    """Per team and unit: the cap share of players who are HERE now and were
    not here last season, priced at last season's cap.

    The counterpart to retention. Retention says how much of the old unit
    survived; this says what was bought to replace it. A team that lost its
    line and signed three expensive linemen should not be shrunk toward the
    league average -- it should be shrunk toward what that money usually buys.

    Cap share is a lagging, noisy proxy for quality: rookie-deal stars are
    underpaid and declining veterans overpaid. It is a prior on the
    replacements, not a measurement of them."""
    import nfl_data_py as nfl
    prior = season - 1
    values = cap_values({prior}).set_index('player_id').cap_percent
    weekly = nfl.import_weekly_rosters([season]).drop_duplicates('player_id')
    weekly['team'] = weekly.team.replace(RELOCATED)
    before = roster_at(prior, 22)
    units = {'receivers': CATCHER_POS, 'backs': BACK_POS, 'oline': OLINE_POS,
             'pass_def': PASS_DEF_POS, 'run_def': RUN_DEF_POS}
    rows = []
    for team, group in weekly.groupby('team'):
        was = before.get(team, {'gsis': set()})['gsis']
        arrived = group[~group.player_id.isin(was)]
        row = dict(season=season, team=team)
        for unit, positions in units.items():
            here = arrived[arrived.position.isin(positions)]
            row[f'{unit}_in'] = values.reindex(here.player_id).fillna(0).sum()
        rows.append(row)
    table = pd.DataFrame(rows)
    # League-relative, because the model's inputs are league z-scores: what
    # matters is spending unusually, not spending.
    for unit in units:
        column = f'{unit}_in'
        spread = table[column].std()
        table[f'{unit}_target'] = ((table[column] - table[column].mean()) / spread) if spread else 0.
    return table


def build_incoming_cap(seasons):
    CACHE.mkdir(parents=True, exist_ok=True)
    table = pd.concat([incoming_cap(s) for s in seasons], ignore_index=True)
    table.to_parquet(CACHE / 'incoming_cap.parquet')
    print(f'{len(table)} team-seasons -> {CACHE / "incoming_cap.parquet"}')
    return table
